<#
.SYNOPSIS
    Full Mode 0 → Mode A TC preparation for OLAC-7502.
    Triggered by: scripts/triggers/OLAC-7502-create-tc.json

    Steps executed:
      1a. Transition sub-task OLAC-7557 to "In Dev"
      0.  Mode 0 Sprint Triage -- check if an existing Xray Test covers OLAC-7502
      A.  Mode A -- fetch story AC, Q&N gate, generate TC doc, create Xray Test
          a.  Post Q&N comment on Xray Test @Tester (if gaps found)
          b.  Add test to sprint Test Execution
          c.  Transition Xray Test to "Ready for Test Review"
      7f3. Transition OLAC-7557 to "Done" (only when Q&N loop is complete)

.USAGE
    cd "C:\Agentic-AI\agentic-ai-powertools-jira-user-new"
    .\scripts\create-tc-olac-7502.ps1

.NOTES
    Generated by test_case_preparation agent on 2026-08-14.
    Jira MCP was unavailable at generation time; this script calls the REST API directly.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# -- Bootstrap ----------------------------------------------------------------
$repoRoot  = Split-Path $PSScriptRoot -Parent
. "$repoRoot\scripts\xray-api.ps1"

$storyKey      = "OLAC-7502"
$subtaskKey    = "OLAC-7557"
$projectKey    = "OLAC"
$sprintSlug    = "CID-sprint-112"
$tcDocDir      = "$repoRoot\docs\TestCases\$sprintSlug"
$tcDocPath     = "$tcDocDir\TC_OLAC-7502.md"
$monitorState  = "$repoRoot\scripts\monitor-state.json"
$triggerFile   = "$repoRoot\scripts\triggers\OLAC-7502-create-tc.json"
$xrayTestSummary = ""

$creds = Get-XrayCreds

Write-Host ""
Write-Host "=" * 70 -ForegroundColor Cyan
Write-Host " TC Preparation: $storyKey -- CID-sprint-112" -ForegroundColor Cyan
Write-Host "=" * 70 -ForegroundColor Cyan

# -----------------------------------------------------------------------------
# STEP 1a -- Transition OLAC-7557 to "In Dev"
# -----------------------------------------------------------------------------
Write-Host "`n[Step 1a] Transitioning $subtaskKey to 'In Dev'..." -ForegroundColor Yellow
$transitioned = Invoke-JiraTransition -IssueKey $subtaskKey -TransitionName "In Dev"
if (-not $transitioned) {
    # Try alternate transition names used by different Jira workflow schemes
    foreach ($altName in @("Dev", "Start Dev", "In Progress", "Start Progress")) {
        Write-Host "  Trying transition '$altName'..."
        $transitioned = Invoke-JiraTransition -IssueKey $subtaskKey -TransitionName $altName
        if ($transitioned) { break }
    }
}
if ($transitioned) {
    Write-Host "  [OK] $subtaskKey transitioned to In Dev." -ForegroundColor Green
} else {
    Write-Warning "  Could not transition $subtaskKey. Check available transitions and transition manually."
}

# -----------------------------------------------------------------------------
# STEP 2 -- Fetch full story detail (description + AC + team + comments)
# -----------------------------------------------------------------------------
Write-Host "`n[Step 2] Fetching story $storyKey from Jira..." -ForegroundColor Yellow
$story = Get-JiraStoryDetail -StoryKey $storyKey
if (-not $story) {
    Write-Error "Cannot read $storyKey from Jira. Check credentials in .vscode/mcp.local.json."
}

Write-Host "  Summary  : $($story.Summary)"
Write-Host "  Comments : $($story.CommentCount)"

$storySummaryClean = [string]$story.Summary
$storySummaryClean = $storySummaryClean -replace '^\s*\d+:\s*',''
$storySummaryClean = $storySummaryClean -replace '(:\s*)\d+:\s*','$1'
$storySummaryClean = $storySummaryClean.Trim()
if (-not $storySummaryClean) { $storySummaryClean = [string]$story.Summary }
$xrayTestSummary = "Test for $storySummaryClean"

# Prefer AC field; fall back to Description section labelled "Acceptance criteria"
$acRaw = [string]$story.AcceptanceCriteria
if (-not $acRaw.Trim()) {
    $desc = [string]$story.Description
    $acSection = ""

    # Capture only the AC section and stop before Design Notes / QA Notes / next section header.
    if ($desc -match "(?is)acceptance\s+criteria\s*\r?\n(?<ac>.*?)(?=\r?\n\s*design\s+notes\b|\r?\n\s*qa\s+notes\b|\r?\n\s*#{1,6}\s|\z)") {
        $acSection = $Matches['ac']
    }

    if ($acSection.Trim()) {
        $acRaw = $acSection.Trim()
    }
}
if (-not $acRaw.Trim()) {
    Write-Error "No Acceptance Criteria found on $storyKey. Cannot generate test cases. Add AC in Jira and re-run."
}

Write-Host ""
Write-Host "  -- Acceptance Criteria ------------------------------------------"
Write-Host $acRaw
Write-Host "  -----------------------------------------------------------------"

# -----------------------------------------------------------------------------
# STEP 2b -- Story Team Discovery (reporter = PO; sub-tasks classify roles)
# -----------------------------------------------------------------------------
Write-Host "`n[Step 2b] Discovering story team..." -ForegroundColor Yellow

$fullIssue = $null
try {
    $resp = Invoke-WebRequest -Method GET `
        -Uri "$($creds.Url)/rest/api/3/issue/$storyKey`?fields=reporter,assignee,subtasks,parent,customfield_10014" `
        -Headers $creds.Headers -UseBasicParsing -ErrorAction Stop
    $fullIssue = ($resp.Content | ConvertFrom-Json).fields
} catch {
    Write-Warning "  Could not fetch reporter/subtasks for $storyKey. Team discovery skipped."
}

$po      = $null
$dev     = $null
$tester  = $null
$tcReviewer = $null

if ($fullIssue) {
    $po = $fullIssue.reporter

    # Classify sub-tasks by summary keywords
    foreach ($st in $fullIssue.subtasks) {
        $stDetail = $null
        try {
            $stResp   = Invoke-WebRequest -Method GET `
                -Uri "$($creds.Url)/rest/api/3/issue/$($st.key)`?fields=summary,assignee,status" `
                -Headers $creds.Headers -UseBasicParsing -ErrorAction Stop
            $stDetail = ($stResp.Content | ConvertFrom-Json).fields
        } catch { continue }

        $stSummary = $stDetail.summary.ToLower()
        $stAssignee = $stDetail.assignee

        if ($stSummary -match "evidence review|sign[- ]off")         { $evidenceReviewer = $stAssignee }
        elseif ($stSummary -match "test.*review|review.*test case")   { $tcReviewer       = $stAssignee }
        elseif ($stSummary -match "develop|implement|code|build")     { $dev              = $stAssignee }
        elseif ($stSummary -match "test|qa|execute|tester")           { $tester           = $stAssignee }
    }

    # Fallbacks
    if (-not $dev)     { $dev     = $fullIssue.assignee }
    if (-not $tester)  { $tester  = $po }                  # last resort; agent will @mention PO
}

Write-Host "  PO       : $(if ($po)         { $po.displayName }       else { 'NOT FOUND' })"
Write-Host "  Dev      : $(if ($dev)        { $dev.displayName }      else { 'NOT FOUND' })"
Write-Host "  Tester   : $(if ($tester)     { $tester.displayName }   else { 'NOT FOUND' })"
Write-Host "  TC Reviewer: $(if ($tcReviewer) { $tcReviewer.displayName } else { 'NOT FOUND' })"

# -----------------------------------------------------------------------------
# MODE 0 -- Sprint Triage
# -----------------------------------------------------------------------------
Write-Host "`n[Mode 0] Sprint Triage -- searching for existing Xray Test..." -ForegroundColor Yellow

$existingTestKey = Find-ExistingXrayTest -StoryKey $storyKey

if ($existingTestKey) {
    $existingStatus = Get-StoryStatus -IssueKey $existingTestKey
    Write-Host "  Found existing Test: $existingTestKey  (Status: $existingStatus)" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  Triage result: ENHANCE existing test $existingTestKey" -ForegroundColor Cyan
    Write-Host "  Routing to Mode B/C. Exiting Mode A." -ForegroundColor Yellow
    Write-Host ""
    Write-Host "  ACTION REQUIRED: Run test_case_review in Mode B (Impact Review) for $existingTestKey."
    exit 0
}

Write-Host "  No existing Test found for $storyKey. Proceeding with Mode A (new TC)." -ForegroundColor Green

# -----------------------------------------------------------------------------
# MODE A -- Parse AC items
# -----------------------------------------------------------------------------
Write-Host "`n[Mode A] Parsing Acceptance Criteria..." -ForegroundColor Yellow

# Parse AC text as paragraph items to preserve wrapped sentences and avoid treating
# section headers (for example Design Notes / QA Notes) as ACs.
$acParagraphs = ($acRaw -replace "`r","") -split "`n\s*`n"
$acItems = @()
$idx = 1
foreach ($p in $acParagraphs) {
    $line = (($p -split "`n") | ForEach-Object { $_.Trim() } | Where-Object { $_ -match '\S' }) -join ' '
    if (-not $line) { continue }

    # Strip common list markers: "- ", "* ", "1. ", "AC-01:", etc.
    $clean = $line -replace '^[-*]\s*','' `
                   -replace '^\d+[\.\)]\s*','' `
                   -replace '^AC-\d+[:\s]+','' `
                   -replace '^\[.\]\s*',''

    if (-not $clean.Trim()) { continue }
    if ($clean -match '^(design notes|qa notes)\b') { continue }

    $acItems += [PSCustomObject]@{
        Id   = "AC-{0:D2}" -f $idx
        Text = $clean.Trim()
    }
    $idx++
}

Write-Host "  Parsed $($acItems.Count) AC item(s):"
$acItems | ForEach-Object { Write-Host "    $($_.Id): $($_.Text)" }

if ($acItems.Count -eq 0) {
    Write-Error "No AC items could be parsed from the story. Verify AC format in Jira and re-run."
}

# -----------------------------------------------------------------------------
# Q&N GATE -- flag gaps before drafting TCs
# -----------------------------------------------------------------------------
Write-Host "`n[Q&N Gate] Checking AC items for ambiguities..." -ForegroundColor Yellow

$qnList     = @()
$blockedACs = @()

foreach ($ac in $acItems) {
    $t = $ac.Text.ToLower()

    # Check 1: External doc/spec referenced but not available
    if ($t -match "see|refer to|as per|per the|according to|documented in") {
        $qnList     += "Q/N for $($ac.Id): References an external document or spec. Please attach or link the referenced document to $storyKey before execution. (Ask: Dev)"
        $blockedACs += $ac.Id
    }

    # Check 2: Hostname/naming scheme TBD
    if ($t -match "tbd|to be confirmed|to be decided|tbc|pending|placeholder") {
        $qnList     += "Q/N for $($ac.Id): Value marked as TBD/TBC. Please confirm the exact value before test execution. (Ask: Dev/PO)"
        $blockedACs += $ac.Id
    }

    # Check 3: Compatibility matrix -- CID version constraints
    if ($t -match "compatib|version|cid.*version|firmware|fr1\.|fr2\.") {
        $qnList     += "Q/N for $($ac.Id): Compatibility matrix or version constraint mentioned. Please confirm which CID firmware versions (FR1.x, FR2.x) are in scope and provide the version list for test data. (Ask: Dev)"
        $blockedACs += $ac.Id
    }

    # Check 4: Certificate chain / CA -- specific chain details needed
    if ($t -match "certificate|cert|ca |pki|chain|trust store") {
        $qnList     += "Q/N for $($ac.Id): Certificate/CA chain details needed. Please confirm: (a) which CA signs the new GenericQA hostname cert, (b) whether the CID agent trust store already includes this CA or requires a Linux Update prereq. (Ask: Dev)"
        $blockedACs += $ac.Id
    }

    # Check 5: Traffic/DNS -- specific hostnames
    if ($t -match "hostname|dns|endpoint|fqdn|\*.cid\.GenericQA|\*.GenericQA\.com") {
        $qnList     += "Q/N for $($ac.Id): New GenericQA FQDN(s) needed for test data. Please confirm the exact production and non-prod (SIT/UAT) hostnames for the Registration/Management API endpoint. (Ask: Dev)"
        $blockedACs += $ac.Id
    }
}

# Deduplicate $blockedACs
$blockedACs = $blockedACs | Sort-Object -Unique

if ($qnList.Count -gt 0) {
    Write-Host "  [Q&N] $($qnList.Count) question(s) identified:" -ForegroundColor Yellow
    $qnList | ForEach-Object { Write-Host "    - $_" }
} else {
    Write-Host "  [Q&N] All AC items clear -- no questions." -ForegroundColor Green
}

# -----------------------------------------------------------------------------
# MODE A -- Generate test steps from AC items
# -----------------------------------------------------------------------------
Write-Host "`n[Mode A] Generating test steps..." -ForegroundColor Yellow

# Each AC generates: 1 happy path step + 1 negative step (minimum)
$steps = @()

foreach ($ac in $acItems) {
    $isBlocked = $blockedACs -contains $ac.Id
    $prefix    = "TC-$storyKey-{0:D2} [$($ac.Id)]" -f ([array]::IndexOf($acItems, $ac) + 1)

    if ($isBlocked) {
        # Blocked step -- create a placeholder
        $steps += @{
            Action   = "$prefix [BLOCKED -- Q/N PENDING]: $($ac.Text)"
            Data     = "BLOCKED -- see Q/N list; test data to be confirmed"
            Expected = "BLOCKED -- expected result depends on Q/N resolution"
        }
    } else {
        # Happy Path step -- derive from AC text
        $steps += @{
            Action   = "$prefix Happy Path: Verify that $($ac.Text -replace '^The ','the ' -replace '^An ','an ')"
            Data     = "Use SIT/non-prod environment; ensure Registration/Management API new GenericQA hostname is configured"
            Expected = $ac.Text
        }

        # Negative/Error step for AC items that imply conditional behaviour
        $t = $ac.Text.ToLower()
        if ($t -match "only|must not|should not|cannot|not allow|prevent|reject|fail|error|block") {
            $steps += @{
                Action   = "$prefix Negative: Attempt operation that violates: $($ac.Text)"
                Data     = "Use invalid/unauthorized input or attempt via old/unconfigured hostname"
                Expected = "Operation is rejected / returns expected error. The prohibited condition does not succeed."
            }
        }

        # Backward-compatibility step for any AC mentioning "legacy" or "existing"
        if ($t -match "legacy|existing|backward|back.compat|old.*hostname|previous") {
            $steps += @{
                Action   = "$prefix Regression: Verify existing (legacy AWS) hostname still works alongside new GenericQA hostname"
                Data     = "Use legacy AWS hostname (*.amazonaws.com) for the Registration/Management API"
                Expected = "CID agent connects successfully via legacy hostname -- no regression for in-field devices not yet updated"
            }
        }
    }
}

# Always add an end-to-end connectivity smoke step
$steps += @{
    Action   = "TC-$storyKey-E2E [All ACs]: End-to-end smoke -- CID registers and connects via new GenericQA domain hostname"
    Data     = "CID device (FR1.0+ firmware); new GenericQA FQDN for Registration/Management API (see Q/N if unconfirmed)"
    Expected = "CID device registers successfully via the new GenericQA-domain hostname. No TLS errors. Activity log records the connection. Existing CIDs not yet updated continue to work via legacy hostname."
}

Write-Host "  Generated $($steps.Count) test step(s)."

# -----------------------------------------------------------------------------
# MODE A -- Build TC document content
# -----------------------------------------------------------------------------
$today = Get-Date -Format "yyyy-MM-dd"

$tcDocContent = @"
# Test Cases -- OLAC-7502: $storySummaryClean

## Document Information

| Field             | Value                                                                 |
|-------------------|-----------------------------------------------------------------------|
| **Story Key**     | ``OLAC-7502``                                                           |
| **Story Summary** | $storySummaryClean |
| **Sprint**        | CID sprint 112                                                        |
| **Prepared By**   | test_case_preparation agent (via create-tc-olac-7502.ps1)             |
| **Date Prepared** | $today                                                                |
| **Status**        | $(if ($blockedACs.Count -gt 0) { "DRAFT -- Q/N PENDING (blocked ACs: $($blockedACs -join ', '))" } else { "Draft" }) |
| **Xray Test Key** | PENDING -- populated when script creates Xray issue                    |

---

## Story Acceptance Criteria

> *Verbatim from OLAC-7502 Jira story (fetched by create-tc-olac-7502.ps1).*

"@

$i = 1
foreach ($ac in $acItems) {
    $blocked = if ($blockedACs -contains $ac.Id) { " ⚠️ Q/N PENDING" } else { "" }
    $tcDocContent += "`n- **$($ac.Id)**:$blocked $($ac.Text)"
    $i++
}

$tcDocContent += @"


---

## Q&N Open Questions

"@

if ($qnList.Count -gt 0) {
    $qi = 1
    foreach ($q in $qnList) {
        $tcDocContent += "`n### Q/N-$($qi.ToString('D2'))`n`n> **PENDING**: $q`n"
        $qi++
    }
    $tcDocContent += @"

> **Action**: Questions posted on Xray Test issue @Tester after Xray issue is created.
> Monitor replies via ``scripts/monitor-po-responses.ps1``.

"@
} else {
    $tcDocContent += "`n> No open questions -- all AC items are clear.`n"
}

$tcDocContent += @"

---

## Test Cases

"@

$tcNum = 1
foreach ($step in $steps) {
    $isBlocked = $step.Action -match '\[BLOCKED'
    $tcId      = "TC-OLAC-7502-{0:D2}" -f $tcNum

    $type = if ($step.Action -match "Negative")  { "Negative" }
            elseif ($step.Action -match "Regression") { "Regression" }
            elseif ($step.Action -match "E2E")    { "Happy Path -- End-to-End" }
            else                                  { "Happy Path" }

    $automation = if ($isBlocked)                           { "No (blocked)" }
                  elseif ($step.Action -match "E2E")        { "Partial" }
                  elseif ($step.Action -match "Negative")   { "Partial" }
                  elseif ($step.Action -match "Regression") { "No" }
                  else                                       { "Yes" }

    # Extract AC ref from step prefix
    $acRef = if ($step.Action -match '\[(AC-\d+)\]') { $Matches[1] } else { "N/A" }

    $tcDocContent += @"

---

### $tcId

| Field           | Value                                  |
|-----------------|----------------------------------------|
| **TC ID**       | ``$tcId``                                |
| **AC Reference**| $acRef                                 |
| **Title**       | $($step.Action -replace "^TC-OLAC-7502-\d+ \[.*?\][:\s]*","" -replace "\[BLOCKED.*","(BLOCKED -- Q/N pending)" ) |
| **Type**        | $type                                  |
| **Priority**    | High                                   |
| **Automation**  | $automation                            |

**Prerequisites**

- Admin or SRE user account with access to the test environment
- Registration/Management API new GenericQA hostname configured in SIT/non-prod
- CID device (FR1.0+) available for connectivity testing

**Test Data**

| Field              | Value                                                                      |
|--------------------|----------------------------------------------------------------------------|
| Story              | OLAC-7502                                                                  |
| Environment        | SIT / non-prod                                                             |
| Test input         | $($step.Data)                                                              |

**Steps**

| Step | Action                                   | Expected Result                          |
|------|------------------------------------------|------------------------------------------|
| 1    | $($step.Action -replace '\|','/')        | $($step.Expected -replace '\|','/')      |

"@

    if ($isBlocked) {
        $tcDocContent += @"

> ⚠️ **BLOCKED**: This test step cannot be finalised until Q/N above is resolved.
> Expected result depends on pending Q/N response. Mark as ``UNCONFIRMED`` in Xray until resolved.

"@
    }

    $tcNum++
}

# AC Coverage Matrix
$tcDocContent += @"

---

## AC Coverage Matrix

| AC Item | Description (brief)                                          | TC IDs Covering It       | Coverage Status |
|---------|--------------------------------------------------------------|--------------------------|-----------------|
"@

$tcNum = 1
foreach ($ac in $acItems) {
    $coveringTCs = @()
    $stepIdx = 1
    foreach ($step in $steps) {
        if ($step.Action -match [regex]::Escape($ac.Id)) {
            $coveringTCs += "TC-OLAC-7502-{0:D2}" -f $stepIdx
        }
        $stepIdx++
    }
    $tcList = if ($coveringTCs.Count -gt 0) { $coveringTCs -join ", " } else { "--" }
    $status = if ($coveringTCs.Count -gt 0) {
        if ($blockedACs -contains $ac.Id) { "⚠️ Covered (Q/N pending)" } else { "✅ Covered" }
    } else { "❌ Not Covered" }

    $brief = if ($ac.Text.Length -gt 80) { $ac.Text.Substring(0,77) + "..." } else { $ac.Text }
    $tcDocContent += "| $($ac.Id)   | $brief | $tcList | $status |`n"
    $tcNum++
}

$tcDocContent += @"

---

## Notes and Assumptions

- This TC was auto-generated by ``create-tc-olac-7502.ps1`` from the story's AC text.
- All test steps require human QA review before execution -- the automation script generates the structure; a QA engineer should verify expected results align with the implemented behaviour.
- "New GenericQA hostname" refers to the FQDN selected during the OLAC-7501 spike (expected: ``*.cid.GenericQA.com`` or similar). Confirm exact FQDN with the Dev team (Q/N above).
- Backward-compatibility steps assume FR1.0+ CID firmware. Confirm trust-store impact with Dev (OLAC-7501 spike findings).
- Sprint TE: to be populated by sprint TE linking step in this script.
"@

# -----------------------------------------------------------------------------
# MODE A -- Save TC document
# -----------------------------------------------------------------------------
Write-Host "`n[Mode A] Saving TC document to $tcDocPath..." -ForegroundColor Yellow

if (-not (Test-Path $tcDocDir)) {
    New-Item -ItemType Directory -Path $tcDocDir -Force | Out-Null
    Write-Host "  Created directory: $tcDocDir"
}

$tcDocContent | Set-Content -Path $tcDocPath -Encoding UTF8 -Force
Write-Host "  Saved: $tcDocPath" -ForegroundColor Green

# -----------------------------------------------------------------------------
# STEP 7 -- Create Xray Test issue in Jira
# -----------------------------------------------------------------------------
Write-Host "`n[Step 7] Creating Xray Test issue in Jira..." -ForegroundColor Yellow

$xrayDescription = "Xray Test for OLAC-7502. Local doc: docs/TestCases/$sprintSlug/TC_OLAC-7502.md"

$xrayResult = Ensure-XrayTest `
    -ProjectKey  $projectKey `
    -Summary     $xrayTestSummary `
    -StoryKey    $storyKey `
    -Steps       $steps `
    -Description $xrayDescription

$xrayTestKey = $xrayResult.Key
$xrayAction  = $xrayResult.Action

if (-not $xrayTestKey) {
    Write-Error "Xray Test creation failed. Check credentials and story status."
}

Write-Host "  Xray Test: $xrayTestKey  (action: $xrayAction)" -ForegroundColor Green

# Update TC doc with Xray Test key
(Get-Content $tcDocPath -Raw -Encoding UTF8) `
    -replace "PENDING -- populated when script creates Xray issue", $xrayTestKey |
    Set-Content $tcDocPath -Encoding UTF8 -Force
Write-Host "  Updated TC doc with Xray Test key: $xrayTestKey"

# Assign Xray Test to tester
if ($tester -and $tester.accountId) {
    try {
        $assignBody = @{ accountId = $tester.accountId } | ConvertTo-Json
        Invoke-RestMethod -Uri "$($creds.Url)/rest/api/3/issue/$xrayTestKey/assignee" `
            -Method PUT -Headers $creds.Headers -Body $assignBody -ErrorAction Stop
        Write-Host "  Assigned $xrayTestKey to $($tester.displayName)" -ForegroundColor Green
    } catch {
        Write-Warning "  Could not assign $xrayTestKey to tester: $_"
    }
}

# -----------------------------------------------------------------------------
# STEP 6a -- Post Q&N on Xray Test @Tester (if questions were collected)
# -----------------------------------------------------------------------------
$qnCommentId = $null
if ($qnList.Count -gt 0 -and $tester) {
    Write-Host "`n[Step 6a] Posting Q&N comment on $xrayTestKey @$($tester.displayName)..." -ForegroundColor Yellow

    $bulletItems = $qnList | ForEach-Object {
        @{
            type    = "listItem"
            content = @(@{ type = "paragraph"; content = @(@{ type = "text"; text = $_ }) })
        }
    }

    $commentBody = @{
        body = @{
            version = 1
            type    = "doc"
            content = @(
                @{
                    type    = "paragraph"
                    content = @(
                        @{ type = "mention"; attrs = @{ id = $tester.accountId; text = "@$($tester.displayName)" } },
                        @{ type = "text"; text = " [QA -- Open Questions for review before execution -- $xrayTestKey]" }
                    )
                },
                @{
                    type    = "bulletList"
                    content = $bulletItems
                },
                @{
                    type    = "paragraph"
                    content = @(@{
                        type  = "text"
                        text  = "Please review each question. If valid, escalate to PO or Dev as appropriate. Questions are also marked as BLOCKED/UNCONFIRMED in the TC doc."
                        marks = @(@{ type = "em" })
                    })
                }
            )
        }
    }

    try {
        $commentResp = Invoke-WebRequest -Method POST `
            -Uri "$($creds.Url)/rest/api/3/issue/$xrayTestKey/comment" `
            -Headers $creds.Headers `
            -Body ($commentBody | ConvertTo-Json -Depth 15) `
            -UseBasicParsing -ErrorAction Stop
        $qnCommentId = ($commentResp.Content | ConvertFrom-Json).id
        Write-Host "  Q&N comment posted on $xrayTestKey. Comment ID: $qnCommentId" -ForegroundColor Green
    } catch {
        Write-Warning "  Could not post Q&N comment on $xrayTestKey`: $_"
    }
} elseif ($qnList.Count -gt 0) {
    Write-Warning "  Q&N questions exist but no tester accountId found. Post Q&N comment manually on $xrayTestKey."
}

# -----------------------------------------------------------------------------
# STEP 7e -- Sprint TE Linkage
# -----------------------------------------------------------------------------
Write-Host "`n[Step 7e] Checking sprint Test Execution linkage..." -ForegroundColor Yellow

# Resolve active sprint for OLAC project (board 440 from monitor-state.json)
$boardId   = 440
$sprintId  = $null
$sprintTEKey = $null

try {
    $sprintResp = Invoke-WebRequest -Method GET `
        -Uri "$($creds.Url)/rest/agile/1.0/board/$boardId/sprint?state=active" `
        -Headers $creds.Headers -UseBasicParsing -ErrorAction Stop
    $activeSprints = ($sprintResp.Content | ConvertFrom-Json).values
    if ($activeSprints -and $activeSprints.Count -gt 0) {
        $sprintId   = $activeSprints[0].id
        $sprintName = $activeSprints[0].name
        Write-Host "  Active sprint: '$sprintName' (ID: $sprintId)"
    }
} catch {
    Write-Warning "  Could not retrieve active sprint for board $boardId`: $_"
}

if ($sprintId) {
    # Use Agile sprint issues API (NOT JQL sprint= filter — fails for Xray TEs)
    # Filter client-side for Test Executions not in a Done status category
    try {
        $startAt = 0; $allIssues = @()
        do {
            $page = Invoke-RestMethod `
                -Uri "$($creds.Url)/rest/agile/1.0/sprint/$sprintId/issue?maxResults=100&startAt=$startAt&fields=summary,status,issuetype" `
                -Headers $creds.Headers -UseBasicParsing
            $allIssues += $page.issues
            $startAt   += $page.issues.Count
        } while ($allIssues.Count -lt $page.total -and $page.issues.Count -gt 0)

        $teIssues = $allIssues | Where-Object {
            $_.fields.issuetype.name -eq 'Test Execution' -and
            $_.fields.status.statusCategory.key -ne 'done'
        }

        if ($teIssues -and $teIssues.Count -gt 0) {
            # Prefer a TE whose summary matches the sprint slug; fall back to newest
            $sprintTE = $teIssues | Where-Object {
                $_.fields.summary -match "Sprint TE|Sprint Test Execution|$sprintSlug"
            } | Select-Object -First 1
            if (-not $sprintTE) { $sprintTE = $teIssues[0] }
            $sprintTEKey = $sprintTE.key
            Write-Host "  Found existing sprint TE: $sprintTEKey -- '$($sprintTE.fields.summary)'"
        } else {
            Write-Host "  No active sprint TE found in sprint $sprintId. Will create one."
        }
    } catch {
        Write-Warning "  Could not retrieve sprint issues for board $boardId`: $_"
    }
}

if ($sprintTEKey) {
    # Add xrayTestKey to existing sprint TE via Xray Cloud GraphQL
    Write-Host "  Adding $xrayTestKey to sprint TE $sprintTEKey..." -ForegroundColor Yellow

    $xrayToken = $null
    try { $xrayToken = Get-XrayCloudToken } catch { Write-Verbose "  Xray Cloud token unavailable." }

    $addedToTE = $false
    if ($xrayToken) {
        try {
            $execIdResp = Invoke-WebRequest -Method GET `
                -Uri "$($creds.Url)/rest/api/2/issue/$sprintTEKey`?fields=id" `
                -Headers $creds.Headers -UseBasicParsing -ErrorAction Stop
            $execId = ($execIdResp.Content | ConvertFrom-Json).id

            $testIdResp = Invoke-WebRequest -Method GET `
                -Uri "$($creds.Url)/rest/api/2/issue/$xrayTestKey`?fields=id" `
                -Headers $creds.Headers -UseBasicParsing -ErrorAction Stop
            $testId = ($testIdResp.Content | ConvertFrom-Json).id

            $gqlHeaders  = @{ Authorization = "Bearer $xrayToken"; "Content-Type" = "application/json" }
            $gqlMutation = "{`"query`":`"mutation { addTestsToTestExecution(issueId: \`"$execId\`", testIssueIds: [\`"$testId\`"]) { addedTests warning } }`"}"
            $gqlResp     = Invoke-WebRequest -Method POST -Uri "https://us.xray.cloud.getxray.app/api/v2/graphql" `
                -Headers $gqlHeaders -Body $gqlMutation -UseBasicParsing -ErrorAction Stop
            $gqlResult   = ($gqlResp.Content | ConvertFrom-Json).data.addTestsToTestExecution

            if ($gqlResult.addedTests) {
                Write-Host "  $xrayTestKey added to sprint TE $sprintTEKey." -ForegroundColor Green
                $addedToTE = $true
            } elseif ($gqlResult.warning) {
                Write-Warning "  Xray warned: $($gqlResult.warning)"
            }
        } catch {
            Write-Warning "  Xray Cloud GraphQL failed when adding test to TE: $_"
        }
    }

    if (-not $addedToTE) {
        # Fallback: Xray Server/DC REST API
        try {
            Invoke-XrayApi -Method POST `
                -Path "/rest/raven/1.0/api/testexec/$sprintTEKey/test" `
                -Creds $creds -Body @{ add = @($xrayTestKey) } | Out-Null
            Write-Host "  $xrayTestKey added to sprint TE $sprintTEKey (via Server API)." -ForegroundColor Green
            $addedToTE = $true
        } catch {
            Write-Warning "  Could not add $xrayTestKey to $sprintTEKey. Add manually."
        }
    }
} else {
    Write-Host "  No existing sprint TE found. Creating a new sprint TE for $sprintSlug..." -ForegroundColor Yellow
    $newTEKey = New-XrayTestExecution `
        -ProjectKey  $projectKey `
        -StoryKey    $storyKey `
        -TestKeys    @($xrayTestKey) `
        -Summary     "Sprint TE: $sprintSlug -- $projectKey" `
        -Environment "SIT"

    $sprintTEKey = $newTEKey
    Write-Host "  Sprint TE created: $sprintTEKey" -ForegroundColor Green

    if ($sprintId) {
        # Move new TE to active sprint
        try {
            $moveBody = @{ issues = @($newTEKey) } | ConvertTo-Json
            Invoke-WebRequest -Method POST `
                -Uri "$($creds.Url)/rest/agile/1.0/sprint/$sprintId/issue" `
                -Headers $creds.Headers -Body $moveBody -UseBasicParsing -ErrorAction Stop | Out-Null
            Write-Host "  Sprint TE $sprintTEKey moved to sprint $sprintId."
        } catch {
            Write-Warning "  Could not move TE to sprint: $_"
        }
    }

    # Sprint TE creation complete — no story comment posted (comments go on the Xray Test only)
}

# -----------------------------------------------------------------------------
# STEP 7f-1 -- Transition Xray Test to "Ready for Test Review" (if no Q&N)
# -----------------------------------------------------------------------------
$xrayFinalStatus = "Open"

if ($qnList.Count -eq 0) {
    Write-Host "`n[Step 7f-1] Transitioning $xrayTestKey to 'Ready for Test Review'..." -ForegroundColor Yellow
    $rftOk = Invoke-JiraTransition -IssueKey $xrayTestKey -TransitionName "Ready for Test Review"
    if ($rftOk) {
        $xrayFinalStatus = "Ready for Test Review"
        Write-Host "  $xrayTestKey  →  Ready for Test Review" -ForegroundColor Green
    } else {
        Write-Warning "  Could not transition to 'Ready for Test Review'. Check available transitions for $xrayTestKey."
    }
} else {
    Write-Host "`n[Step 7f-2] Q&N questions are open -- NOT transitioning to 'Ready for Test Review'." -ForegroundColor Yellow
    Write-Host "  $xrayTestKey remains in Open/Draft status until Q&N resolved."
    Write-Host "  Q&N comment posted on Xray Test (ID: $qnCommentId)."
    Write-Host "  Monitor for replies: scripts/monitor-po-responses.ps1"
}

# -----------------------------------------------------------------------------
# STEP 7f-3 -- Transition OLAC-7557 to "Done" (only when Q&N loop complete)
# -----------------------------------------------------------------------------
if ($qnList.Count -eq 0) {
    Write-Host "`n[Step 7f-3] Transitioning $subtaskKey to 'Done'..." -ForegroundColor Yellow
    $doneOk = Invoke-JiraTransition -IssueKey $subtaskKey -TransitionName "Done"
    if (-not $doneOk) {
        foreach ($altName in @("Closed", "Resolved", "Complete")) {
            $doneOk = Invoke-JiraTransition -IssueKey $subtaskKey -TransitionName $altName
            if ($doneOk) { break }
        }
    }
    if ($doneOk) {
        Write-Host "  $subtaskKey  →  Done" -ForegroundColor Green
    } else {
        Write-Warning "  Could not transition $subtaskKey to Done. Transition manually once Q&N resolved."
    }
} else {
    Write-Host "`n[Step 7f-3] SKIP: $subtaskKey stays 'In Dev' -- Q&N loop not yet complete." -ForegroundColor Yellow
}

# -----------------------------------------------------------------------------
# UPDATE monitor-state.json
# -----------------------------------------------------------------------------
Write-Host "`n[Monitor] Updating monitor-state.json..." -ForegroundColor Yellow

$ms = Get-Content $monitorState -Raw | ConvertFrom-Json

# Update or insert OLAC-7502 entry
$entry = $ms.issues | Where-Object { $_.issueKey -eq $storyKey }
if (-not $entry) {
    # Add new entry
    $newEntry = [PSCustomObject]@{
        issueKey       = $storyKey
        xrayTestKey    = $xrayTestKey
        sprintSlug     = $sprintSlug
        tcDocPath      = "docs/TestCases/$sprintSlug/TC_OLAC-7502.md"
        tcrDocPath     = "docs/TestCaseReview/TCR_OLAC-7502.md"
        status         = "ACTIVE"
        tcDocStatus    = if ($qnList.Count -gt 0) { "DRAFT_QN_PENDING" } else { "DRAFT_READY_FOR_REVIEW" }
        blockedStep    = if ($qnList.Count -gt 0) { ($qnList | ForEach-Object { $_ -replace ".*Q/N for (AC-\d+).*",'$1' } | Sort-Object -Unique) -join "," } else { $null }
        qnCommentId    = $qnCommentId
        qnPostedAt     = if ($qnCommentId) { (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ") } else { $null }
        qnAskedOf      = if ($tester) { "$($tester.displayName) (tester)" } else { $null }
        xrayExecutionKey = $sprintTEKey
        detectedChanges = @()
        lastSeenStatus = "In Dev"
        automationTarget = "TBD"
        team           = @{
            po         = if ($po)         { @{ displayName = $po.displayName;      accountId = $po.accountId      } } else { $null }
            dev        = if ($dev)        { @{ displayName = $dev.displayName;     accountId = $dev.accountId     } } else { $null }
            tester     = if ($tester)     { @{ displayName = $tester.displayName;  accountId = $tester.accountId  } } else { $null }
            tcReviewer = if ($tcReviewer) { @{ displayName = $tcReviewer.displayName; accountId = $tcReviewer.accountId } } else { $null }
        }
        tcDocCreatedAt = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
        lastSeenUpdated = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
    }
    $ms.issues = @($ms.issues) + @($newEntry)
    Write-Host "  Added new entry for $storyKey."
} else {
    $entry.xrayTestKey       = $xrayTestKey
    $entry.sprintSlug        = $sprintSlug
    $entry.tcDocPath         = "docs/TestCases/$sprintSlug/TC_OLAC-7502.md"
    $entry.status            = "ACTIVE"
    $entry.tcDocStatus       = if ($qnList.Count -gt 0) { "DRAFT_QN_PENDING" } else { "DRAFT_READY_FOR_REVIEW" }
    $entry.blockedStep       = if ($qnList.Count -gt 0) { ($qnList | ForEach-Object { $_ -replace ".*Q/N for (AC-\d+).*",'$1' } | Sort-Object -Unique) -join "," } else { $null }
    $entry.qnCommentId       = $qnCommentId
    $entry.xrayExecutionKey  = $sprintTEKey
    $entry.lastSeenUpdated   = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
    Write-Host "  Updated existing entry for $storyKey."
}

$ms | ConvertTo-Json -Depth 15 | Set-Content $monitorState -Encoding UTF8 -Force
Write-Host "  monitor-state.json saved." -ForegroundColor Green

# Mark trigger file as processed
$trigger = Get-Content $triggerFile -Raw | ConvertFrom-Json
$trigger | Add-Member -NotePropertyName "processedAt" -NotePropertyValue (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ") -Force
$trigger | Add-Member -NotePropertyName "xrayTestKey" -NotePropertyValue $xrayTestKey -Force
$trigger | Add-Member -NotePropertyName "status"      -NotePropertyValue "PROCESSED"  -Force
$trigger | ConvertTo-Json -Depth 5 | Set-Content ($triggerFile -replace '\.json$', '.json.processed') -Encoding UTF8 -Force
Write-Host "  Trigger file marked as processed."

# -----------------------------------------------------------------------------
# SUMMARY
# -----------------------------------------------------------------------------
Write-Host ""
Write-Host "=" * 70 -ForegroundColor Cyan
Write-Host " TC Preparation Complete -- $storyKey" -ForegroundColor Cyan
Write-Host "=" * 70 -ForegroundColor Cyan
Write-Host ""
Write-Host "  Xray Test      : $xrayTestKey  (status: $xrayFinalStatus)"
Write-Host "  Sprint TE      : $sprintTEKey"
Write-Host "  TC Document    : docs/TestCases/$sprintSlug/TC_OLAC-7502.md"
Write-Host "  Steps created  : $($steps.Count)"
Write-Host "  Q&N questions  : $($qnList.Count)"
Write-Host "  Sub-task       : $subtaskKey  →  $(if ($qnList.Count -eq 0) { 'Done' } else { 'In Dev (awaiting Q/N)' })"
Write-Host ""

if ($qnList.Count -gt 0) {
    Write-Host "  NEXT STEPS:" -ForegroundColor Yellow
    $testerName = if ($tester) { $tester.displayName } else { 'UNKNOWN' }
    Write-Host "    1. Tester ($testerName) reviews Q&N comment on $xrayTestKey"
    Write-Host "    2. Tester escalates to Dev/PO as appropriate"
    Write-Host "    3. When all questions resolved: re-run this script OR manually:"
    Write-Host "       a. Update blocked TC steps in TC doc"
    Write-Host "       b. Update Xray Test steps via Set-XrayCloudTestSteps"
    Write-Host "       c. Invoke-JiraTransition -IssueKey $xrayTestKey -TransitionName 'Ready for Test Review'"
    Write-Host "       d. Invoke-JiraTransition -IssueKey $subtaskKey -TransitionName 'Done'"
} else {
    Write-Host "  All steps complete. $xrayTestKey is Ready for Test Review." -ForegroundColor Green
    Write-Host "  TC Reviewer can begin review against docs/TestCases/$sprintSlug/TC_OLAC-7502.md"
}
Write-Host ""
